/**
 * Módulos del sistema
 */
export const MODULOS = {
  ENCUESTAS: 'ENCUESTAS',
  USUARIOS: 'USUARIOS',
  ZONAS: 'ZONAS',
  CLIENTES: 'CLIENTES',
  CONTACTO: 'CONTACTO',
  REPORTES: 'REPORTES',
} as const;

/**
 * Rutas de los módulos
 */
export const RUTAS_MODULOS: Record<string, string> = {
  [MODULOS.ENCUESTAS]: '/encuestas',
  [MODULOS.USUARIOS]: '/usuarios',
  [MODULOS.ZONAS]: '/zonas',
  [MODULOS.CLIENTES]: '/clientes',
  [MODULOS.CONTACTO]: '/contacto',
  [MODULOS.REPORTES]: '/reportes',
};

/**
 * Categorías de parámetros
 */
export const CATEGORIAS_PARAMETROS = {
  MODULOS: 'MODULOS',
  ESTADO_ENCUESTA: 'ESTADO_ENCUESTA',
  TIPO_ENCUESTA: 'TIPO_ENCUESTA',
  TAMANO_EMPRESA: 'TAMANO_EMPRESA',
  TIPO_EMPRESA: 'TIPO_EMPRESA',
  LUGAR_COMPRA: 'LUGAR_COMPRA',
  TIPO_COMPRA_CEMENTO: 'TIPO_COMPRA_CEMENTO',
  TIPO_PRESENTACION_BOLSA: 'TIPO_PRESENTACION_BOLSA',
  TIPO_PRESENTACION_GRANEL: 'TIPO_PRESENTACION_GRANEL',
  CANTIDAD_PRESENTACION_BOLSA: 'CANTIDAD_PRESENTACION_BOLSA',
  CANTIDAD_PRESENTACION_BOMBONA: 'CANTIDAD_PRESENTACION_BOMBONA',
  CANTIDAD_PRESENTACION_BIGBAG: 'CANTIDAD_PRESENTACION_BIGBAG',
  MEDIO_CONTACTO: 'MEDIO_CONTACTO',
} as const;
